[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "learn-backend-course"
version = "0.1.0"
description = "A comprehensive backend development course project"
authors = [
    {name = "Your Name", email = "your.email@example.com"},
]
dependencies = [
    "fastapi[standard]==0.135.1",
    "uvicorn==0.41.0",
    "pydantic==2.12.5",
    "pydantic-settings==2.13.1",
    "SQLAlchemy==2.0.48",
    "alembic==1.18.4",
    "psycopg2==2.9.11",
    "python-jose==3.3.0",
    "passlib==1.7.4",
    "bcrypt==4.1.2",
    "python-multipart==0.0.22",
    "email-validator==2.3.0",
    "python-dotenv==1.2.2",
    "httpx==0.28.1",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[tool.hatch.build.targets.wheel]
packages = ["app"]

[tool.fastapi]
entrypoint = "app.main:app"